version: '3.3'

services:
   wordpress:
     depends_on:
       - wordpress-db
     image: wordpress:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_DATABASE: wordpress_db
       WORDPRESS_DB_PASSWORD: wordpress_password

   wordpress-db:
     image: mysql:5.7
     volumes:
       - ./mysql_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       WORDPRESS_DB_DATABASE: wordpress_db
       MYSQL_PASSWORD: wordpress_password
volumes:
    mysql_data:
      driver: local
